name: hackathon_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.0
  flutter: ^3.38.1

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: 6.1.1
  speech_to_text: 7.3.0
  permission_handler: 11.3.0
  vibration: 3.1.3
  cupertino_icons: 1.0.8
  flutter_secure_storage: 9.2.4
  riverpod: 3.0.3
  freezed: 3.2.3
  go_router: 17.0.0
  flutter_hooks: 0.21.2
  hooks_riverpod: 3.0.3
  riverpod_annotation: 3.0.3
  json_annotation: 4.9.0
  freezed_annotation: 3.1.0
  audioplayers: 6.5.1
  google_fonts: 6.3.2
  flutter_native_splash: 2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  riverpod_generator: 3.0.3
  build_runner: 2.10.4
  json_serializable: 6.11.2
  custom_lint: 0.8.1
  riverpod_lint: 3.0.3
  flutter_launcher_icons: 0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/chara/
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/app_icon.png
  android_12:
    icon_background_color: "#ffffff"
    image: assets/icon/app_icon.png
