name: Flutter CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*.dart"

jobs:
  flutter-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6.0.0

      - uses: subosito/flutter-action@v2.21.0
        with:
          channel: stable

      - name: Install packages
        run: flutter pub get

      - name: Flutter lint
        run: flutter analyze

      - name: Riverpod lint
        run: dart run custom_lint

